### ISSUE TITLE
Authentication code

### ISSUE THREAD

**Issue by seanwoodward33** [Krazy998/mqtt-hisensetv#10]
Hi,
Thanks for your useful guide, I've been using it to connect to my Hisense TV.
When I first connected to the TV and tried to get the TV state my TV came up on the screen with a 4 digit conformation code that I had to submit before I could send any further commands. I couldn't find how to publish this code from your code but have worked it out by piecing together several other bits of code I found online.

A user would need to publish
/remoteapp/tv/ui_service/HomeAssistant/actions/authenticationcode
{"authNum": XXXX}
where XXXX is the 4 digit number displayed on the screen. Once this pairing has been completed, the user than then send the other commands to change channel, power off etc.

I thought you might want to update your readme file to include this, as I thought it might be useful to some other users too.

Thanks for your work, it's been really helpful.

Cheers,

Sean

**Comment by Krazy998** [comment]
Sorry for the slow update - I have added this! thanks!
