### ISSUE TITLE
Retrieving currently selected source

### ISSUE THREAD

**Issue by UncleLeoTheDad** [Krazy998/mqtt-hisensetv#11]
Thanks so much for documenting this!  Has anyone figured out how to get the currently selected source?  I know you can get the source list, but I was hoping to also get the selected source.  Thanks!

**Comment by Krazy998** [comment]
Publish:
/remoteapp/tv/ui_service/HomeAssistant/actions/gettvstate

Subscribe:
/remoteapp/mobile/broadcast/ui_service/state
JSON output:
{"statetype":"sourceswitch","sourceid":"4",**"sourcename":"HDMI** 2","is_signal":1,"is_lock":0,"hotel_mode":0,"displayname":"HDMI 2"}
