### ISSUE TITLE
Publish request for TV Status not working

### ISSUE THREAD

**Issue by mariley2250** [Krazy998/mqtt-hisensetv#12]
We have a 5 TV Video wall setup at work. I am using MQTT to control all the tvs synchronously, all is working well but if the tvs get out of sync as in 2 TVs are on and 3 are off then using SEND_KEY to power off or WOL to power on then a toggle switch does not work. To elevate this I have been trying to get the TV State via MQTT to allow me to know the state and change the way the control operates. 

Am i right in thinking i should get a response when i publish: 
/remoteapp/tv/ui_service/[SOME_MAC_ADDRESS]/actions/gettvstate

The document states i should use: /remoteapp/tv/ui_service/HomeAssistant/actions/gettvstate

but i have replaced the "HomeAssistant" part with the authorized Mac address from my phone. 

any assistance would be appreciated.

**Comment by mariley2250** [comment]
bump

**Comment by Krazy998** [comment]
Yes that should work, but will only work if the tv is actually on. You will not get a state if its off. You could probably write something, like if no response assume its off.

**Comment by mariley2250** [comment]
This problem is not solved
