### ISSUE TITLE
MQTT connection to 65E7HQ QLED

### ISSUE THREAD

**Issue by maxpd1** [Krazy998/mqtt-hisensetv#13]
Hi, 

I am trying to connect to a new Hisense 65E7HQ QLED with Vidaa 5.

Very simple setup with MQTT explorer for fast initial connection, exactly according to your description

![image](https://user-images.githubusercontent.com/15956503/213846373-e1e59486-f095-480e-839e-9ae0f9470dc7.png)

![image](https://user-images.githubusercontent.com/15956503/213846434-811b4f83-8d59-4907-b801-e1fe1bca1d18.png)

But connection can't be established. Do you see any mistakes?

Regards
maxpd

**Comment by Krazy998** [comment]
that looks fine. Just double check certificates. Also suggest checking out the home assistant thread as many people have different models and needed to do slight modifications to the process to make it work (hisense has been changing the approach slightly with newer models)

https://community.home-assistant.io/t/hisense-tv-control/97638/290
