### ISSUE TITLE
Hissende H55nec6500

### ISSUE THREAD

**Issue by govabm** [Krazy998/mqtt-hisensetv#3]
Hello everyone,

I have a Problem with my TV NEC6500 I can't connect the TV with the MQTT.

Does someone know a solution for my Problem

**Comment by Krazy998** [comment]
You will need to provide a little bit more information. Have you tried connecting with a MQTT client to the TV? 

Is TCP port 36669 open on the TV? If so have you tried making sure you have encryption enabled in the client and also to ignore the certificate?

**Comment by govabm** [comment]
Yes we tried with mqtt Client to the tv.
On the tv i dont Open a Port How?
I cant set in the Menü Open Port or something i only cam set wake on lan and or wlan.


Von meinem iPhone gesendet

**Comment by govabm** [comment]
How i Open the Port on my tv ? 
Control via mobile  app works 
Can we fix ist via   mqtt.fx if yes How ?????

Von meinem iPhone gesendet

**Comment by Krazy998** [comment]
what i meant was you need to test from your computer to see if TCP port 36669 is open on the TV. That would hopefully tell us if its running MQTT.

I would recommend you try connecting to the TV with SSL/TLS enabled in the client, but you will need to find a mqtt client that can disable certificate checking or import the TV's SSL certificate.

As I dont have this TV my help is limited. You may want to check https://community.home-assistant.io/t/hisense-tv-control/97638 as there have been plenty of people that maybe have solved it or have a better chance of someone else having it done on that particular TV Model
