### ISSUE TITLE
not really an issue but would this work for the UST projector?

### ISSUE THREAD

**Issue by gbdavidx** [Krazy998/mqtt-hisensetv#6]
I have a 

Hisense 100L5F 100" 4K Smart TV
--

**Comment by Krazy998** [comment]
Difficulty to say as I dont own one. Couple of ways to determine if its possible.

1. check that port 36669 is open on the 100L5F device by trying to connect to the devices IP and port from another device on the same network.
2. Are you able to manage the device using the hisense remote app on your mobile device? 

If any of those are true then i suspect this same approach should work on this device.
