### ISSUE TITLE
Minor change to topic format

### ISSUE THREAD

**Issue by cameroncros** [Krazy998/mqtt-hisensetv#9]
I have a Hisense 55R7.

On my TV, most of the information is correct (it has the certificate issue, but that was solvable).

But, the topics are slightly different:

Currently, your doco has PowerOff as:
`/remoteapp/tv/remote_service/AutoHTPC/actions/sendkey`

What I found was that this didnt work, but instead, the "AutoHTPC" section was replaced with "AA:BB:CC:DD:EE:FF$normal", where AA:BB:CC:DD:EE:FF is some kind of MAC address (Possibly phone MAC address, but its not one that is linked to my wifi, so not really sure). It seems to be a device ID of some kind.

I dont know if there is a registration step or something required to setup the AutoHTPC/HomeAssistant device ID or something, but I will keep investigating and update this ticket if I find a solution.

**Comment by Krazy998** [comment]
Hisense has tried to clamp down on its implementation of MQTT and started doing MAC address checking (so you only connect from your phone). There is more details on it in the Hisense thread here: https://community.home-assistant.io/t/hisense-tv-control/97638/290
